parameters:
    ace.editor:
       theme: 'ace/theme/monokai'
       mode: 'ace/mode/php'
       font_size: 16

services:
    app.twig.ace_editor_readonly_extension:
        class: Application\Bundle\CoreBundle\Twig\AceEditorReadOnlyExtension
        arguments:
            [@service_container]
        calls:
            - [setParams, [%ace.editor%]]
        tags:
            - { name: twig.extension }

    app.add_solution_type.form:
        class: Application\Bundle\CoreBundle\Form\Type\AddSolutionType
        arguments: [@security.context]
        calls:
            - [setParams, [%ace.editor%]]

    app.solution:
        class: Application\Bundle\CoreBundle\Service\SolutionService
        arguments:
            - @app.repository.solution
