parameters:
    ace.editor:
       theme: 'ace/theme/eclipse'
       mode: 'ace/mode/html'
       font_size: 14

services:
    app.twig.ace_editor_readonly_extension:
        class: Application\Bundle\CoreBundle\Twig\AceEditorReadOnlyExtension
        arguments:
            [@service_container]
        calls:
            - [setParams, [%ace.editor%]]
        tags:
            - { name: twig.extension }

    app.add_solution_type.form:
        class: Application\Bundle\CoreBundle\Form\Type\AddSolutionType
        calls:
            - [setParams, [%ace.editor%]]