application_user:
    resource: "@ApplicationUserBundle/Resources/config/routing.yml"
    prefix:   /

application_core:
    resource: "@ApplicationCoreBundle/Controller/"
    type: annotation
    prefix: /

fos_comment_api:
    type: rest
    resource: "@FOSCommentBundle/Resources/config/routing.yml"
    prefix: /api
    defaults: { _format: html }
