application_comment:
    resource: "@ApplicationCommentBundle/Resources/config/routing.yml"
    prefix:   /

application_core:
    resource: "@ApplicationCoreBundle/Resources/config/routing.yml"
    prefix:   /

