application_user:
    resource: "@ApplicationUserBundle/Resources/config/routing.yml"
    prefix:   /

application_core:
    resource: "@ApplicationCoreBundle/Controller/"
    type: annotation
    prefix: /

