security:
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        default:
            anonymous: ~

        secured_area:
            pattern: ^/auth
            oauth:
                failure_path: /auth/connect
                login_path: /auth/connect
                check_path: /auth/connect
                provider: fos_userbundle
                resource_owners:
                    my_github:          "/login/check-github"
                login_path:        /login
                use_forward:       false
                failure_path:      /login

                oauth_user_provider:
                    service: application_user.user.provider.fosub_bridge

            anonymous: true
            logout:
                path:   /auth/logout
                target: /auth/connect #where to go after logout

    access_control:
        - { path: ^/auth/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/auth/connect, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/auth, roles: ROLE_USER }

