parameters:
    application_user.user.provider.class: Application\Bundle\UserBundle\Security\Provider\AuthProvider

services:
    application_user.user.provider:
        class: %application_user.user.provider.class%
        arguments: [@fos_user.user_manager, {github: githubId}]
