services:
    application_user.user.provider.fosub_bridge:
        class: Application\Bundle\UserBundle\Security\Core\User\FOSUserProvider
        arguments: [@fos_user.user_manager, {my_github: githubId}]
